# React Service
apiVersion: v1
kind: Service
metadata:  
  name: test-react-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: 127.0.0.1:30000/webui:v0.1
        ports:
          - name: http-port
            containerPort: 80

---

# React Instance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-react-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-react-service
  template:
    metadata:
      labels:
        app: test-react-service
    spec:
      containers:
      - name: react-test-image
        image: "react-image:v.$BUILD_NUMBER" // This will publish to docker hub .. BUILD_NUMBER is dynamic versioning from Jenkins
        ports:
            - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
